window.RECRUITING_CONFIG = {
  schoolName: "Clarksburg High School Football",
  coachName: "Brandon Martin",
  coachTitle: "Varsity Head Coach",
  formUrl: "https://docs.google.com/forms/d/e/1FAIpQLSeriRFMczhVUkoQSaspjLnNTgao_iZtxNaH-AA3LOCjWXn0kQ/viewform",
  recruiterInquiryUrl: "https://docs.google.com/forms/d/e/1FAIpQLSeJdPVMuAWzWNhwZSS6vqk7kYniM5OV9qu7GNzvBa1DfRjdIA/viewform",
  dataMode: "remote",
  remoteDataUrl: "https://script.google.com/macros/s/AKfycbwW6HR1PMUaWdymqZbBzX9UsTuIxsohqtzzcbtypFTo8P3p8Uj40tAntPB4m3f8Ex3N/exec",
  remoteJsonpUrl: "https://script.google.com/macros/s/AKfycbwW6HR1PMUaWdymqZbBzX9UsTuIxsohqtzzcbtypFTo8P3p8Uj40tAntPB4m3f8Ex3N/exec",
  localDataUrl: "./data/athletes.json",
  coachEmail: "brandon_c_martin@mcpsmd.org",
  coachPhone: "(240) 728 - 3501",
  displayCoachDirectContact: false,
  schoolAddress: "22500 Wims Road, Clarksburg, MD 20871",
  schoolMapUrl: "https://maps.google.com/?q=22500+Wims+Road,+Clarksburg,+MD+20871",
  maxPrepsUrl: "https://www.maxpreps.com/md/clarksburg/clarksburg-coyotes/football/",
  publicContactNote: "Recruiters can request athlete contact, transcripts, and additional information through our recruiting request form.",
};
